#!/bin/bash

echo "🚂 Deploying Backend to Railway"
echo "==============================="

echo "Go to: https://railway.app/"
echo ""
echo "OPTION 1: FREE TIER"
echo "- \$5 free credits monthly"
echo "- Perfect for starting out"
echo "- 500MB RAM, 1GB storage"
echo ""
echo "OPTION 2: PAID TIER (\$5/month + usage)"
echo "- Better performance and reliability"
echo "- 8GB RAM, unlimited storage"
echo "- 99.9% uptime guarantee"
echo ""
echo "1. Sign up with GitHub"
echo "2. Click 'Deploy from GitHub repo'"
echo "3. Connect your repository"
echo "4. Select the backend folder"
echo ""
echo "5. Add these environment variables:"
echo "   SHOPIFY_STORE_DOMAIN=j0dktb-z1.myshopify.com"
echo "   SHOPIFY_STOREFRONT_ACCESS_TOKEN=d6663c23c4c7b1c85790bb6230722ee2"
echo "   MONGO_URL=[Your MongoDB connection string]"
echo "   DB_NAME=undhyu_db"
echo "   PORT=8001"
echo ""
echo "6. Click Deploy!"
echo ""
echo "📝 Your backend URL will be: https://yourapp.up.railway.app"
echo "💡 Save this URL - you'll need it for Vercel!"

read -p "Press Enter when your Railway backend is deployed..."