#!/bin/bash

echo "⚡ Deploying Frontend to Vercel"
echo "==============================="

echo "Go to: https://vercel.com/"
echo ""
echo "OPTION 1: HOBBY (FREE)"
echo "- Unlimited static sites"
echo "- 100GB bandwidth"
echo "- Perfect for ecommerce"
echo ""
echo "OPTION 2: PRO (\$20/month)"
echo "- Analytics and insights"
echo "- Better performance"
echo "- Priority support"
echo ""
echo "1. Sign up with GitHub"
echo "2. Click 'New Project'"
echo "3. Import your repository"
echo "4. Configure:"
echo "   - Framework Preset: Create React App"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: build"
echo ""
echo "5. Add environment variable:"
echo "   REACT_APP_BACKEND_URL=[Your Railway backend URL]"
echo ""
echo "6. Click Deploy!"
echo ""
echo "📝 Your frontend URL will be: https://yourapp.vercel.app"
echo "💡 This will be used for your custom domain!"

read -p "Press Enter when your Vercel frontend is deployed..."