#!/bin/bash

echo "🍃 Setting up MongoDB Atlas for Undhyu.com"
echo "==========================================="

echo "1. Go to: https://cloud.mongodb.com/"
echo "2. Click 'Try Free' or 'Sign Up'"
echo "3. Choose 'Shared' (FREE) or 'Dedicated' (PAID for better performance)"
echo ""
echo "FREE TIER: M0 - 512MB storage (Perfect for starting)"
echo "PAID UPGRADE: M10 - $9/month (2GB, better performance)"
echo ""
echo "4. Create cluster with these settings:"
echo "   - Cluster Name: undhyu-db"
echo "   - Region: Choose closest to your customers"
echo "   - Version: 7.0 (latest)"
echo ""
echo "5. Create Database User:"
echo "   - Username: undhyu-admin"
echo "   - Password: [Generate strong password]"
echo ""
echo "6. Network Access:"
echo "   - Add IP: 0.0.0.0/0 (Allow from anywhere)"
echo ""
echo "7. Get Connection String:"
echo "   - Click 'Connect' → 'Connect your application'"
echo "   - Copy the connection string"
echo ""
echo "📋 Your connection string will look like:"
echo "mongodb+srv://undhyu-admin:<password>@undhyu-db.xxxxx.mongodb.net/"
echo ""
echo "💡 Save this connection string - you'll need it for Railway!"

read -p "Press Enter when you have your MongoDB connection string ready..."