#!/bin/bash

echo "🌐 Connecting Undhyu.com Domain"
echo "==============================="

echo "In your Vercel dashboard:"
echo "1. Go to your project settings"
echo "2. Click 'Domains'"
echo "3. Add 'undhyu.com'"
echo "4. Add 'www.undhyu.com'"
echo ""
echo "DNS Configuration at your domain registrar:"
echo "============================================="
echo ""
echo "Type: A"
echo "Name: @"
echo "Value: 76.76.19.61"
echo "TTL: 300"
echo ""
echo "Type: CNAME"  
echo "Name: www"
echo "Value: cname.vercel-dns.com"
echo "TTL: 300"
echo ""
echo "🔒 SSL Certificate will be automatically generated!"
echo "⏱️ DNS propagation takes 5-10 minutes"
echo ""
echo "🎉 Your website will be live at:"
echo "   https://undhyu.com"
echo "   https://www.undhyu.com"

read -p "Press Enter when DNS is configured..."